### ISSUE TITLE
eCobidas: because methods writing is too important (and boring) to let humans do it!

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/global2020#45]
## Project info

**Title:**
eCOBIDAS: a webApp to that writes your methods section for you

**Project lead:**
- Rémi Gau
- Brainhack Mattermost: @remi-Gau
- Twitter: [@RemiGau](https://twitter.com/RemiGau) 

**Project collaborators:**
Many ! And hopefully even more after you join !
All contributors are listed on the repository [HERE](https://github.com/Remi-Gau/eCobidas#contributors-) and in this [spreadsheet](https://docs.google.com/spreadsheets/d/1v_ReviQZLNxg9T5qCYAfMiA-rZupMnWp03PSNVRGpBI/edit?usp=sharing)

I try to keep the spreadsheet up to date at every event and I plan to use it to automate making a longer "Contributors" page for the repository. 

**Registered Brainhack Global 2020 Event:**
- Donostia
- Marseille
- Ankara

**Project Description:**
The main aim of this project is to improve reporting methods and results in neuroimaging (f/MRI, i/EEG, MEG, PET...) in order to increase transparency and reproducibility.

We want to do this by developing a set webapps to run checklists:
- based on best practices guidelines and recommendation of a field
- that are both easy and practical to use, 
- that provides a machine readable summary of an experiment and its analysis
- that can then automatically generate parts of the methods section.

**Data to use:**
No data will be used.

**Link to project repository/sources:**
https://github.com/Remi-Gau/eCobidas

Documentation: https://remi-gau.github.io/eCobidas/

fMRI prototype app: 
 - repo: https://github.com/ohbm/cobidas
 - webApp: https://ohbm.github.io/cobidas/#/

PET prototype app: 
 - repo: https://github.com/Remi-Gau/cobidas-PET
 - webApp: https://remi-gau.github.io/cobidas-PET/#/

eyetracking prototype app: 
 - repo: https://github.com/Remi-Gau/cobidas-eyetracker
 - webApp: https://remi-gau.github.io/cobidas-eyetracker/#/

**Goals for Brainhack Global 2020:**

**Good first issues:**

Several "good first issues" [here](https://github.com/Remi-Gau/eCobidas/labels/good%20first%20issue) but I would like to focus on:

1. Making sure the documenation is understandable and constitute good on-board and How-To materieal
2. Create some prototype script / toy example that can take the output of the app and generate a method section

**NOTE** : I created empty issued where I want to describe better the goals of those 2 issues.

**Skills:**

The project has many moving parts so there is a certain level of flexibility in terms of skills needed:

- a certain love handling and tidying up spreadsheets: the source of the project starts in [several spreadsheets](https://drive.google.com/drive/u/0/folders/1ydwALHDzl21dcef3qhkju8JKKAT3Y72V) that are then read by a python script to create the questions for the webApp

**Communication channels:**

 

**Project labels**

- [x] I added all of the labels I want associated to my project

### Submission checklist

*Once the issue is submitted, please check items in this list as you add under ‘Additional project info’*

- [x] Link to your project: could be a code repository, a shared document, etc.

- [x] Goals for Brainhack Global 2020: describe what you want to achieve during this brainhack.

- [ ] Flesh out at least 2 “good first issues”: those are tasks that do not require any prior knowledge about your project, could be defined as issues in a GitHub repository, or in a shared document.

- [ ] Skills: list skills that would be particularly suitable for your project. We ask you to include at least one non-coding skill. Use the issue labels for this purpose.

Optionally, you can also include information about:

- [ ] Number of participants required.

- [ ] Twitter-size summary of your project pitch.

- [x] Provide an image of your project for the Brainhack Global 2020 website. 

I need to work on a better one than that (that could be part of this project actually), but here you go: Image: 

![ ](https://raw.githubusercontent.com/Remi-Gau/eCobidas/master/docs/img/checklist.jpg)

We would like to think about how you will credit and onboard new members to your project. If you’d like to share your thoughts with future project participants, you can include information about:

- [x] Specify how you will acknowledge contributions (e.g. listing members on a contributing page).

- [x] Provide links to onboarding documents if you have some: the documentation is the closest thing I have to an onboarding document at the moment -  https://remi-gau.github.io/eCobidas/

**Comment by Remi-Gau** [comment]
# TO DO

- [ ] describe needed skills better
- [ ] describe what skills can be gained
- [x] actually write the issues for this BHG

**Comment by Remi-Gau** [comment]
Does it make sense to add "labels" in plain text in the issue, even if they will not be picked up by github actions?

**Comment by SamGuay** [comment]
Thanks for the submission ^^ 

> Does it make sense to add "labels" in plain text in the issue, even if they will not be picked up by github actions?

In fact, if you put # in front of any labels, it will be picked up by the GH actions no matter where it appears in the issue. As long as it is properly written, it should be fine. Regarding your question, it is up to you. If you think it makes sense, go ahead and add them in the body of the issue.

**Comment by eurunuela** [comment]
Thank you so much for your submission @Remi-Gau !

I guess this one is ready to be published too @SamGuay !

**Comment by Remi-Gau** [comment]
I still need to work on those "first issues" but I won't be able to make progress on those before Wednesday but if you want to go ahead and publish already I am of course all in favor. :-)

**Comment by eurunuela** [comment]
I'd publish it so we take it into account for the brainmatch algorithm. This way, we'll be able to suggest the top 3 matching projects to each of our participants.

The GFI can be edited later, it's okay 😉

**Comment by Remi-Gau** [comment]
FYI: I have updated the locations since I will be running the project in parallel in 2 events. (Trying to make the most of the virtual format).

- Marseille
- Ankara

**Comment by complexbrains** [comment]
Oh, that's fantastic news! We kept discussing how to work on the continuity of the projects across the events to be addressed. You served and easy solution for us indeed :hugs: thank you Remi! It will be so exciting!

**Comment by Remi-Gau** [comment]
> Oh, that's fantastic news! We kept discussing how to work on the continuity of the projects across the events to be addressed. You served and easy solution for us indeed hugs thank you Remi! It will be so exciting!

Sort of hoping that some of the people who helped me in Donostia will come back for a couple of hours. It would be really nice to create that continuity.
