### ISSUE TITLE
Relating EEG eye-tracking data to attention network subsystems

### ISSUE THREAD

**Issue by emilyolafson** [brainhackorg/global2020#87]
## Project info

**Title:** Relating eye-tracking EEG metrics to attention network systems

**Project lead:** Emily Olafson, mattermost: @emilyo email: olafsonemily@gmail.com 

**Project collaborators:** Sudhin Shah

**Registered Brainhack Global 2020 Event:** Brainhack NY, USA

**Project Description:** This project involves analysis eye-tracking EEG data that was recorded during the Attention Network Task, a paradigm used to assess different components of attention. Each of the primary attention systems—alerting, orienting, and executive control monitoring—involves salient autonomic correlates as evidenced by changes in reactive pupil dilation and blinks. The goal of the project will be to understand how physiological correlates of attention vary in healthy individuals and in patients with traumatic brain injury (TBI). 

**Data to use:**
The data consists of EEG outputs in the form of .edf files which include pupil dilation and eye-blinks, as well as accompanying behavioural data (Attention Network Task) including measures like reaction time. The data was collected by Dr. Sudhin Shah at Weill Cornell Medicine.

**Link to project repository/sources:**

https://github.com/emilyolafson/eyetrack-ANT

**Goals for Brainhack Global 2020:**

Assess all ANT trial eye-tracking data to identity outliers/poor quality trials, look for differences in eye-tracking metrics across age and diagnosis, relate eye-tracking metrics to behaviour (i.e. reaction time).

**Good first issues:**

1. Extract reaction time and accuracy measures from ANT (Attention Network Task) outputs for each subject and for each session.
2. Import .edf EEG data files to MATLAB and perform a quality check for each session (i.e. bad quality = eye gaze leaves the field)

**Skills:** Python or MATLAB skills at any level, statistics, familiarity with EEG 

**Tools/Software/Methods to Use:**
Python, MATLAB

**Communication channels:**
https://mattermost.brainhack.org/brainhack/channels/eyetracking-project
https://meet.jit.si/EyeTrackingProject

**Project labels**

- [x] I added all of the labels I want an associate to my project

### Submission checklist

*Once the issue is submitted, please check items in this list as you add under ‘Additional project info’*

- [x] Link to your project: could be a code repository, a shared document, etc.
- [x] Goals for Brainhack Global 2020: describe what you want to achieve during this brainhack.
- [x] Flesh out at least 2 “good first issues”: those are tasks that do not require any prior knowledge about your project, could be defined as issues in a GitHub repository, or in a shared document.
- [x] Skills: list skills that would be particularly suitable for your project. We ask you to include at least one non-coding skill. Use the issue labels for this purpose.
- [x] Chat channel: A link to a chat channel that will be used during the Brainhack Global 2020 event. This can be an existing channel or a new one. We recommend using the [Brainhack space on Mattermost](https://mattermost.brainhack.org/).

Optionally, you can also include information about:

- [ ] Number of participants required.
- [x] Twitter-sized summary of your project pitch: "In this project, pupil dilation and eye-blinks recorded during an attention task will be related to behaviour in a sample of healthy individuals and patients with traumatic brain injury."

- [x] Provide an image of your project for the Brainhack Global 2020 website. 

![eyetrack](https://user-images.githubusercontent.com/39418731/101557241-97347680-398a-11eb-8036-a314448d27c5.png)

We would like to think about how you will credit and onboard new members to your project. If you’d like to share your thoughts with future project participants, you can include information about:

- [ ] Specify how you will acknowledge contributions (e.g. listing members on a contributing page).
- [ ] Provide links to onboarding documents if you have some:

**Comment by complexbrains** [comment]
Dear @emilyolafson That's an amazing project! Thank you so much for submitting it. 🎉 

I was just wondering would you like to provide these listed below for the completion of the review which would give more detailed information to the attendees we believe if you could kindly provide please. 

- Link to project repository/sources
- Goals for Brainhack Global 2020
- and an image for your project for us to list it at Brainhack Global webpage with a card associated with it as in [here](https://brainhack.org/global2020/projects/)

As soon as you complete those we will publish your project on the website and will add it to our twitter thread. 

Thank you 🤗

**Comment by emilyolafson** [comment]
Hi @Brainhack-Global/project-monitors: my project is ready!
